version: 2
updates:
- package-ecosystem: npm
  schedule:
    interval: monthly
    time: '10:40'
    timezone: Australia/Melbourne
  open-pull-requests-limit: 5
  groups:
    npm-development-dependencies:
      applies-to: version-updates
      dependency-type: development
      patterns:
      - "*"
      update-types:
      - minor
      - patch
    npm-production-minor-patch:
      applies-to: version-updates
      dependency-type: production
      patterns:
      - "*"
      update-types:
      - minor
      - patch
    npm-security:
      applies-to: security-updates
      patterns:
      - "*"
  directory: "/"
- package-ecosystem: github-actions
  schedule:
    interval: monthly
    time: '10:50'
    timezone: Australia/Melbourne
  open-pull-requests-limit: 5
  directory: "/"
  groups:
    actions-minor-patch:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - minor
      - patch
    actions-major:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - major
    actions-security:
      applies-to: security-updates
      patterns:
      - "*"
